// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALU4yNP7P_KGcm6rmVX-ecaoxCo48b1nM',
    appId: '1:710015075476:web:083be9af87eb8e1add2081',
    messagingSenderId: '710015075476',
    projectId: 'casandes-b7cbe',
    authDomain: 'casandes-b7cbe.firebaseapp.com',
    storageBucket: 'casandes-b7cbe.firebasestorage.app',
    measurementId: 'G-DWS21M8S11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqM3mAJ9pr0gpcg3OBwW0qhge2x-AFr1Q',
    appId: '1:710015075476:android:46c7a58c9b18a32ddd2081',
    messagingSenderId: '710015075476',
    projectId: 'casandes-b7cbe',
    storageBucket: 'casandes-b7cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Tw9RmkXRgO8WTMx8bYp__rLa_yNYPn8',
    appId: '1:710015075476:ios:db651b3b84542d8cdd2081',
    messagingSenderId: '710015075476',
    projectId: 'casandes-b7cbe',
    storageBucket: 'casandes-b7cbe.firebasestorage.app',
    iosBundleId: 'com.example.housingAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Tw9RmkXRgO8WTMx8bYp__rLa_yNYPn8',
    appId: '1:710015075476:ios:db651b3b84542d8cdd2081',
    messagingSenderId: '710015075476',
    projectId: 'casandes-b7cbe',
    storageBucket: 'casandes-b7cbe.firebasestorage.app',
    iosBundleId: 'com.example.housingAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALU4yNP7P_KGcm6rmVX-ecaoxCo48b1nM',
    appId: '1:710015075476:web:d096cc2eb3681d87dd2081',
    messagingSenderId: '710015075476',
    projectId: 'casandes-b7cbe',
    authDomain: 'casandes-b7cbe.firebaseapp.com',
    storageBucket: 'casandes-b7cbe.firebasestorage.app',
    measurementId: 'G-26M0YE1JMY',
  );
}
